import 'package:test/test.dart';

import '../bin/8/main.dart';

void main() {
  test("day 8 part 1 - 1 ", () {
    final input = """
..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
.........."""
        .split("\n")
        .toList();

    expect(countAntinodes(input), 2);
  });

  test("day 8 part 1 - 2 ", () {
    final input = """
..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
.........."""
        .split("\n")
        .toList();

    expect(countAntinodes(input), 4);
  });

  test("day 8 part 1 - 3", () {
    final input = """
..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
.........."""
        .split("\n")
        .toList();

    expect(countAntinodes(input), 4);
  });

  test("day 8 part 1 - 4", () {
    final input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        .split("\n")
        .toList();

    expect(countAntinodes(input), 14);
  });

  test("day 8 part 2 - 1", () {
    final input = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
.........."""
        .split("\n")
        .toList();

    expect(countAntinodesWithHarmonics(input), 9);
  });

  test("day 8 part 2 - 2", () {
    final input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        .split("\n")
        .toList();

    expect(countAntinodesWithHarmonics(input), 34);
  });
}
